### ISSUE TITLE
Confirm docs for api based contract verification

### ISSUE THREAD

**Issue by jcvernaleo** [hemilabs/frontend#11]
### Description

The documentation on the api docs seem to refer to the v2 api while hardhat verification uses the v1 api
https://testnet.explorer.hemi.xyz/api/
vs
https://testnet.explorer.hemi.xyz/api/v2/

We need to confirm that the api docs properly show how to verify contracts (which we have confirmed does work).

### Link to the page

https://testnet.explorer.hemi.xyz/api-docs

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### App version

Frontend: e43825ed

### Operating system

None

**Comment by gabmontes** [comment]
The [contract verification UI](https://testnet.explorer.hemi.xyz/contract-verification) seems to use API v2.

@jcvernaleo Where is HardHat verification pointing to the v1?

**Comment by jcvernaleo** [comment]
Yeah, I'm not 100% sure what was reported.  I looks like the docs are in order (and this is being added to the hemi docs site where it is easier to access anyway).  So closing this one.
